server:
  # I do not use default port here
  port: 8082
  tomcat:
    # Will create tomcat-log directory inside your project. You can choose different locations here, i.e.: /var/log/propmtpay/tomcat
    basedir: logs/tomcat
    accesslog:
      enabled: true
      directory: logs
    # Maximum amount of worker threads in server under top load. In other words, maximum number of simultaneous requests that can be handled.
    max-threads: 400
    # Time that connectors wait for another HTTP request before closing the connection. When not set, the connector’s container-specific default is used. Use a value of -1 to indicate infinite timeout.
    connection-timeout: 5s
    # The minimum number of threads always kept running. This includes both active and idle threads.
    min-spare-threads: 10
    max-swallow-size: 2MB
    # Maximum size of the HTTP post content.
    max-http-form-post-size: 2MB
    # Maximum number of connections that the server accepts and processes at any given time.
    max-connections: 10000
    # Maximum queue length for incoming connection requests when all possible request processing threads are in use.
    accept-count: 100
  servlet:
    contextPath: /api
  max-http-header-size: 8KB

spring:
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:pvexample_db;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        trace: false
        web-allow-others: true
  liquibase:
    change-log: classpath:/db/changelog-master.xml

  jpa:
    # For production recommended to keep as false
    show-sql: false
    hibernate:
      ddl-auto: validate

## Logging
logging:
  file:
    # Will create pvexample-log directory inside your project. You can choose different locations here, i.e: /var/log/pvexample
    path: logs/pvexample
  level:
    lt:
      asprogramuoju: TRACE
    org:
      springframework: ERROR
      # if you wan't to see parameters
      hibernate:
        type: error
        stat: off
